refactoring: refactor build and deploy process

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,11 +1,17 @@
 #!/bin/bash
 
-# build BUILD_TASK COMMIT_ID
+# build SRC_DIR BUILD_TASK BRANCH
+
+#TODO:
+# * check input params
+# * remove docker images even on error
 
 set -eo pipefail
+set -x
 
 SOURCE_DIR="$1"
 APP="$2"          # build_task / job_name
+BRANCH="$3"
 
 export QBUILD_ROOT=${QBUILD_ROOT:="/var/tmp/qbuild"}
 mkdir -p $QBUILD_ROOT
@@ -20,26 +26,24 @@ fi
 
 DOCKER_IMAGE=$(ruby -e "require 'yaml';puts YAML.load_file('$APP')['image'] || 'lksv/qbuild-node'")
 
-#
 uid=`id -u`
 gid=`id -g`
-script="groupadd --gid $gid ubuntu && useradd --uid $uid --gid $gid ubuntu; su ubuntu -c "
+script="groupadd --gid $gid ubuntu && useradd --uid $uid --gid $gid --create-home --shell /bin/dash ubuntu; sudo -u ubuntu -H sh -c "
 
 
 echo "----> Building  $APP (dockeer: $DOCKER_IMAGE)"
 
 # Run the builder script and attach to view output
-ID=$(docker run -d -v $SOURCE_DIR:/app -v $CACHE_DIR:/cache -w /app $DOCKER_IMAGE /build/builder "$APP")
+ID=$(docker run -d -v $SOURCE_DIR:/app -v $CACHE_DIR:/cache -w /app $DOCKER_IMAGE sh -c "$script \"/build/builder $APP\"")
 docker attach $ID
 test $(docker wait $ID) -eq 0
 docker rm $ID
 
 
+MATCH_BRANCH=$(ruby -e "require 'yaml';puts (YAML.load_file('$APP')['deploy'] || {})['branch']")
 DEPLOY_PORT=$(ruby -e "require 'yaml';puts (YAML.load_file('$APP')['deploy'] || {})['port']")
-DEPLOY_SCRIPT=$(ruby -e "require 'yaml';puts (YAML.load_file('$APP')['deploy'] || {})['script']")
 
-if [ -n "$DEPLOY_PORT" ]; then
-  set -x
+if [ -n "$DEPLOY_PORT" -a "$BRANCH" = "$MATCH_BRANCH" ]; then
   echo "-----> Deploying $APP on port $DEPLOY_PORT"
 
   if [[ -f "$QBUILD_ROOT/$APP/CONTAINER" ]]; then
@@ -65,7 +69,7 @@ if [ -n "$DEPLOY_PORT" ]; then
     sleep 5
   fi
 
-  ID=$(docker run -d -p $DEPLOY_PORT -v $SOURCE_DIR:/app -v $CACHE_DIR:/cache -w /app $DOCKER_IMAGE build/deployer "$APP")
+  ID=$(docker run -d -p $DEPLOY_PORT -v $SOURCE_DIR:/app -v $CACHE_DIR:/cache -w /app $DOCKER_IMAGE sh -c "$script \"/build/deployer $APP\"")
   #docker attach $ID
   echo $ID > "$QBUILD_ROOT/$APP/CONTAINER"
 
