wip: deploy and correct user setup

diff --git a/qbuild-node/builder/deployer b/qbuild-node/builder/deployer
--- a/qbuild-node/builder/deployer
+++ b/qbuild-node/builder/deployer
@@ -32,11 +32,13 @@ mkdir -p /app/.profile.d
 if [[ -f "$1" ]]; then
   #ruby -e "require 'yaml';(YAML.load_file('$1')['env'] || {}).each{|k,v| puts \"export #{k}='#{v}'\"}" > /app/.profile.d/00_config_vars.sh
   ruby -e "require 'yaml';(YAML.load_file('$1')['env'] || {}).each{|k,v| puts \"export #{k}\"}" > /app/.profile.d/00_config_vars.sh
-  ruby -e "require 'yaml'; Array(YAML.load_file('$1')['dependencies']).join(\"\\n\")" > /app/.profile.d/100_dependences.sh
+else
+  echo "QBuild meta file '$1' is missing.";
+  exit 1
 fi
 
-SCRIPT_FILE=$1.build_script.sh
+SCRIPT_FILE=$1.deployer_script.sh
 
-ruby -e "require 'yaml';puts Array(YAML.load_file('$1')['script']).join(\"\\n\")" > $SCRIPT_FILE
+ruby -e "require 'yaml';puts (YAML.load_file('$1')['deploy'] || {})['script']" > $SCRIPT_FILE
 
 sudo -u $user_name -H sh -c "/build/exec $SCRIPT_FILE"
